name: Build under Ubuntu

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11 and 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            11
            17

      - name: Build server with JVM 11 and run tests
        run: ./gradlew build --stacktrace
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-11

      - name: Build client with JVM 17
        run: ./desktop/gradlew build --stacktrace
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17
