name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Publish package
        # Since we're in the `master` branch already, this means that tests of a PR passed.
        # So, no need to run the tests again when publishing.
        run: ./gradlew publish -x test --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
